name: CMake Build

on:
  push:
    branches: [ test-github-actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Windows-specific setup
    - name: Set up vcpkg (Windows only)
      if: runner.os == 'Windows'
      uses: lukka/run-vcpkg@v11
      with:
        runVcpkgInstall: true
        vcpkgConfigurationJsonGlob: '**/vcpkg-configuration.json'
        vcpkgDirectory: 'C:/Users/runneradmin/vcpkg'
        vcpkgJsonGlob: '**/vcpkg.json'


    - name: Set up CUDA (Windows only)
      if: runner.os == 'Windows'
      run: |
        choco install cuda --version=12.1 --yes

    # Linux-specific setup
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswresample-dev cmake g++ needrestart

    - name: Configure needrestart (Linux)
      if: runner.os == 'Linux'
      run: |
        echo "NEEDRESTART_MODE=a" | sudo tee /etc/needrestart/needrestart.conf

    - name: Install CUDA (Linux)
      if: runner.os == 'Linux'
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-repo-ubuntu2004_12.1.0-1_amd64.deb
        sudo dpkg -i cuda-repo-ubuntu2004_12.1.0-1_amd64.deb
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
        sudo apt-get update
        sudo apt-get install -y cuda

    - name: Add CUDA to PATH (Linux)
      if: runner.os == 'Linux'
      run: |
        echo "/usr/local/cuda-12.1/lib64" >> $GITHUB_ENV
        echo "/usr/local/cuda-12.1/bin" >> $GITHUB_PATH

    - name: Create build directory
      run: cmake -B build -S .

    # Windows-specific CMake configuration
    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE=C:/Users/runneradmin/vcpkg/scripts/buildsystems/vcpkg.cmake -B build -S .

    # Linux-specific CMake configuration
    - name: Configure CMake (Linux)
      if: runner.os == 'Linux'
      run: |
        cmake -B build -S .

    # Build for both Windows and Linux
    - name: Build with CMake
      run: cmake --build build

    # Run tests (optional)
    - name: Run tests
      run: |
        cd build && ctest
