name: Release and Benchmark Tests

on:
  push:
    branches: [master]
    paths:
      - 'dist/**'  # Trigger the workflow when files in dist/ change
  workflow_dispatch:  # Allows manual triggering

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Detect New Version
        id: get_version
        run: |
          # Extract the version from the wheel filename
          VERSION=$(ls dist/*.whl | grep -oP 'ffmpy-\K[0-9]+\.[0-9]+\.[0-9]+')
          echo "New version detected: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        if: always()
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          body: "Automated release of version ${{ env.VERSION }}"
          draft: false
          prerelease: false
          files: |
            dist/*.whl
            dist/*.tar.gz

  test:
    needs: release  # Run after the release job finishes
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests torch opencv-python-headless numpy
          pip install https://github.com/${{ github.repository }}/releases/download/v${{ env.VERSION }}/ffmpy-${{ env.VERSION }}-py3-none-any.whl

      - name: Run video processing tests
        run: |
          cd tests/python
          python test2.py
          python test3.py
