name: Release and Benchmark Tests

on:
  push:
    branches: [master]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine

      - name: Set Version
        id: set_version
        run: |
          VERSION=$(date +"%Y.%m.%d")
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Build the Packages
        run: |
          python build.py --version ${{ env.version }}

      - name: Create GitHub Release
        if: always()
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.version }}
          name: v${{ env.version }}
          body: "Automated release of version ${{ env.version }}"
          draft: false
          prerelease: false
          artifacts: |
            dist/*.whl
            dist/*.tar.gz
        continue-on-error: true

      - name: Handle Existing Tag (Optional)
        if: failure()
        run: |
          echo "Release tag already exists. Skipping release creation."

  publish-to-pypi:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Twine
        run: |
          python -m pip install --upgrade twine

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI}}
        run: |
          twine upload dist/*
