name: Release and Benchmark Tests

on:
  push:
    branches: [master]
    paths:
      - 'setup.py'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Detect New Version from setup.py
        id: get_version
        shell: bash
        run: |
          version=$(python setup.py --version)
          echo "New version detected: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Build the package
        run: |
          pip install setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Create GitHub Release
        if: always()
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.version }}
          name: v${{ env.version }}
          body: "Automated release of version ${{ env.version }}"
          draft: false
          prerelease: false
          artifacts: |
            dist/*.whl
            dist/*.tar.gz
