name: Release and Benchmark Tests

on:
  push:
    branches: [master]
    paths:
      - 'dist/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Detect New Version
        id: get_version
        shell: pwsh
        run: |
          $version = (Get-ChildItem dist\*.whl | Select-String -Pattern 'ffmpy-(\d+\.\d+\.\d+)').Matches.Groups[1].Value
          Write-Output "New version detected: $version"
          echo "version=$version" >> $env:GITHUB_ENV  # Use environment files

      - name: Create GitHub Release
        if: always()
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.version }}
          name: v${{ env.version }}
          body: "Automated release of version ${{ env.version }}"
          draft: false
          prerelease: false
          artifacts: |
            dist/*.whl
            dist/*.tar.gz
