name: Release and Benchmark Tests

on:
  push:
    branches: [main]
    paths:
      - 'dist/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Detect New Version
        id: get_version
        shell: pwsh
        run: |
          $version = (Get-ChildItem dist\*.whl | Select-String -Pattern 'ffmpy-(\d+\.\d+\.\d+)').Matches.Groups[1].Value
          Write-Output "New version detected: $version"
          echo "::set-output name=version::$version"  # Use set-output to pass version
        continue-on-error: false  # Ensure script fails if the version is not found

      - name: Create GitHub Release
        if: always()
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.get_version.outputs.version }}
          name: v${{ steps.get_version.outputs.version }}
          body: "Automated release of version ${{ steps.get_version.outputs.version }}"
          draft: false
          prerelease: false
          artifacts: |
            dist/*.whl
            dist/*.tar.gz

  test:
    needs: release
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests torch opencv-python-headless numpy
          pip install https://github.com/${{ github.repository }}/releases/download/v${{ needs.release.outputs.version }}/ffmpy-${{ needs.release.outputs.version }}-py3-none-any.whl

      - name: Run video processing tests
        run: |
          cd tests/python
          python test2.py
          python test3.py
