name: Auto Test

on:
  push:

jobs:
  test:
    runs-on: windows-latest  # Use windows GPU-enabled runner or install CUDA toolkit manually

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install CUDA Toolkit
      run: |
        # Download and install NVIDIA CUDA Toolkit 12.1
        choco install cuda -y --version=12.1

    - name: Verify CUDA installation
      run: |
        nvcc --version
        nvidia-smi

    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: c:\hostedtoolcache\windows\python\3.12.7\x64\lib\site-packages
        key: ${{ runner.os }}-pip-${{ hashFiles('tests/requirements-runner.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
        pip install -r tests/requirements-runner.txt

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel

    - name: Install the package
      run: |
        Get-ChildItem -Path dist -Filter *.whl | ForEach-Object { pip install $_.FullName }

    - name: Run video processing test
      run: |
        cd tests/python
        python test2.py
        python test3.py
